# Generated by uncoded — do not edit; regeneration overwrites.
# tools/forbid_invisible_characters.py

import sys
import unicodedata
from collections.abc import Iterator, Sequence
from pathlib import Path

INVISIBLE_CATEGORY = 'Cf'

def describe(*, character: str) -> str:
    ...

def invisible_characters(*, text: str) -> Iterator[tuple[int, int, str]]:
    ...

def main(*, paths: Sequence[str]) -> int:
    ...
