# Generated by uncoded — do not edit; regeneration overwrites.
# tools/require_keyword_parameters.py

import ast
import sys
from collections.abc import Iterator, Sequence
from pathlib import Path

RECEIVERS = ('self', 'cls')

def is_called_by_pytest(*, definition: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    ...

def positional_parameters(*, text: str) -> Iterator[str]:
    ...

def main(*, paths: Sequence[str]) -> int:
    ...
