# Generated by uncoded — do not edit; regeneration overwrites.
# tests/clocks.py

from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta

PINNED = datetime(2026, 8, 19, 18, 41, 58, tzinfo=UTC)

class Ticking:
    step: float = 1
    readings: list[datetime] = field(default_factory=list)

    def __call__(self) -> datetime:
        ...
