# Generated by uncoded — do not edit; regeneration overwrites.
# tests/conftest.py

import os
from functools import partial
from pathlib import Path
import fakes
import pytest
from dreamcatcher.commands import run
from dreamcatcher.config import CONFIG_NAME

ARMING = 'PYTHONWARNDEFAULTENCODING'
CONFIG_HEAD = 'interval = 300\n\n'
SMITH_CLAUDE = ...
SMITH_CODEX = ...
CONFIG = CONFIG_HEAD + SMITH_CLAUDE + SMITH_CODEX

def pytest_configure(config: pytest.Config) -> None:
    ...

def git(*arguments: str, cwd: Path) -> str:
    ...

def commit(path: Path, message: str) -> None:
    ...

def repo(tmp_path):
    ...

def upstream(tmp_path):
    ...

def cloned(upstream, tmp_path):
    ...

def watched(repo):
    ...

def fake(tmp_path, monkeypatch):
    ...
