# Generated by uncoded — do not edit; regeneration overwrites.
# tests/conftest.py

import os
import subprocess
from pathlib import Path
import pytest
from dreamcatcher.config import CONFIG_NAME

ARMING = 'PYTHONWARNDEFAULTENCODING'
CONFIG_HEAD = 'interval = 300\nharness = "claude"\n\n'
SMITH_CLAUDE = ...
SMITH_CODEX = ...
CONFIG = CONFIG_HEAD + SMITH_CLAUDE + SMITH_CODEX

def pytest_configure(config: pytest.Config) -> None:
    ...

def git(*arguments: str, cwd: Path) -> str:
    ...

def repo(tmp_path):
    ...

def watched(repo):
    ...
