# Generated by uncoded — do not edit; regeneration overwrites.
# tests/conftest.py

import os
import subprocess
from pathlib import Path
import pytest

ARMING = 'PYTHONWARNDEFAULTENCODING'

def pytest_configure(config: pytest.Config) -> None:
    ...

def git(*arguments: str, cwd: Path) -> str:
    ...

def repo(tmp_path):
    ...
