# Generated by uncoded — do not edit; regeneration overwrites.
# tests/fakes.py

import json
import os
import stat
import sys
from dataclasses import asdict, dataclass
from enum import StrEnum
from pathlib import Path
from time import sleep

UNSCRIPTED = 97

def recorded(path: Path) -> list[Line]:
    ...

def install(directory: Path, program: str) -> Fake:
    ...

def replay(base: Path, arguments: list[str]) -> int:
    ...

def _launcher(base: Path) -> None:
    ...

def _scripted(base: Path) -> Path:
    ...

def _scripted_for(base: Path, arguments: list[str]) -> dict | None:
    ...

def _taken(base: Path) -> Path:
    ...

def _append(path: Path, line: dict) -> None:
    ...

def _lines(path: Path) -> list[dict]:
    ...

class Stream(StrEnum):
    OUT = 'stdout'
    ERR = 'stderr'

class Line:
    text: str
    stream: Stream = Stream.OUT

class Call:
    arguments: list[str]
    directory: Path
    prompt: str

class Fake:
    base: Path
    calls: list[Call]

    def replies(self, stdout: str, *, to: str) -> None:
        ...

    def fails(self, stderr: str, status: int, *, to: str) -> None:
        ...

    def streams(self, lines: list[Line], delay: float, status: int, *, to: str) -> None:
        ...

    def _answer(self, lines: list[Line], status: int, delay: float, to: str) -> None:
        ...
