# Generated by uncoded — do not edit; regeneration overwrites.
# tests/fakes.py

import json
import os
import stat
import sys
from dataclasses import dataclass
from pathlib import Path

UNSCRIPTED = 97

def install(directory: Path, program: str) -> Fake:
    ...

def replay(base: Path, arguments: list[str]) -> int:
    ...

def _launcher(base: Path) -> None:
    ...

def _scripted(base: Path) -> Path:
    ...

def _taken(base: Path) -> Path:
    ...

def _append(path: Path, line: dict) -> None:
    ...

def _lines(path: Path) -> list[dict]:
    ...

class Call:
    arguments: list[str]
    directory: Path

class Fake:
    base: Path
    calls: list[Call]

    def replies(self, stdout: str) -> None:
        ...

    def fails(self, stderr: str, status: int) -> None:
        ...

    def _answer(self, stdout: str, stderr: str, status: int) -> None:
        ...
