# Generated by uncoded — do not edit; regeneration overwrites.
# tests/records.py

from pathlib import Path
from dreamcatcher import rounds, sessions
from dreamcatcher.config import Harness
from dreamcatcher.documents import write_json
from dreamcatcher.state import StateDirectory

def write_session(state: StateDirectory, key: str, issue: int) -> Path:
    ...

def write_round(directory: Path, number: int, record: rounds.RoundRecord) -> rounds.RoundRecord:
    ...
