# Generated by uncoded — do not edit; regeneration overwrites.
# tests/recordings.py

from collections.abc import Iterable
from dreamcatcher.adapters import Adapter
from dreamcatcher.feed import Renderer

def rendered(adapter: Adapter, lines: Iterable[str], renderer: Renderer) -> str:
    ...
