# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_fakes.py

from time import perf_counter
import pytest
from fakes import Line, Stream, recorded
from dreamcatcher.commands import CommandError, run

STREAM = '{"type":"assistant","text":"café"}\n{"type":"result"}\n'

def recording(tmp_path):
    ...

def test_a_stand_in_harness_replays_the_recording_it_was_given(fake, recording):
    ...

def test_a_stand_in_harness_streams_at_the_pace_it_was_given(fake, recording):
    ...

def test_a_stand_in_harness_writes_each_line_to_the_stream_it_names(fake):
    ...

def test_a_stand_in_harness_can_end_as_a_failed_round_does(fake, recording):
    ...

def test_a_stand_in_nobody_scripted_says_so(fake):
    ...

def test_a_stand_in_answers_each_call_with_the_rule_that_call_opens(fake):
    ...

def test_a_stand_in_prefers_the_rule_scripted_for_the_particular_call(fake):
    ...

def test_a_call_no_rule_answers_says_the_stand_in_was_not_scripted(fake):
    ...
