# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_words.py

from datetime import timedelta
import pytest
from clocks import PINNED
from dreamcatcher.words import describe_count, describe_span, describe_time

def test_a_time_is_written_the_one_way_the_tool_writes_one():
    ...

def test_a_span_reads_in_the_largest_unit_that_says_it(span, described):
    ...

def test_a_count_reads_for_one_or_for_more_than_one(number, described):
    ...
