# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_clock.py

from datetime import UTC, timedelta
import pytest
from dreamcatcher.clock import describe_span, now

def test_the_clock_reads_in_utc():
    ...

def test_a_span_reads_in_the_largest_unit_that_says_it(span, described):
    ...
