# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_commands.py

import sys
from pathlib import Path
import pytest
from fakes import Line, Stream
from dreamcatcher.commands import CommandError, _quote, locate, refuse_unquotable, run, spawn

def test_a_command_hands_back_what_it_printed(fake):
    ...

def test_a_command_runs_where_it_is_told(fake, tmp_path):
    ...

def test_a_program_on_the_path_is_found(fake):
    ...

def test_a_program_that_is_not_on_the_path_says_so():
    ...

def test_a_failure_carries_the_command_and_what_it_said(fake):
    ...

def test_a_failure_that_said_nothing_still_names_the_command(fake):
    ...

def test_a_command_that_prints_bytes_that_are_not_utf_8_still_reads():
    ...

def test_an_argument_a_second_reader_would_act_on_still_arrives_whole(fake):
    ...

def test_a_spawned_command_runs_where_it_is_told_and_streams_as_it_goes(fake, tmp_path):
    ...

def test_a_spawned_command_finds_its_stdin_already_at_an_end(tmp_path):
    ...

def test_a_quoted_part_hides_what_a_second_reader_would_act_on():
    ...

def test_a_quote_in_a_part_is_doubled():
    ...

def test_a_part_ending_in_a_backslash_does_not_escape_its_closing_quote():
    ...

def test_a_backslash_before_a_quote_is_doubled_so_the_quote_still_counts():
    ...

def test_text_holding_a_percent_sign_is_refused():
    ...

def test_text_holding_a_newline_is_refused():
    ...

def test_text_holding_a_carriage_return_is_refused():
    ...

def test_text_holding_more_than_one_of_them_names_every_one():
    ...

def test_text_the_quoting_carries_comes_back_as_it_was():
    ...
