# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_wakeups.py

from datetime import timedelta
import pytest
from clocks import PINNED
from conftest import POST_LIST_PATHS, POSTED_AT, POSTED_BY, PULL_REQUEST, REPOSITORY, comment, pages, pull_requests
from records import write_round, write_session
from dreamcatcher.github import PullRequestState
from dreamcatcher.prompts import CARRY_ON_PROMPT, MARKER
from dreamcatcher.relay import Inbox
from dreamcatcher.rounds import Cause, Ending, RoundRecord
from dreamcatcher.sessions import advance_watermark, read_sessions
from dreamcatcher.state import NO_ROUND_HAS_RUN, StateDirectory, WaitingSession
from dreamcatcher.wakeups import Wakeup, judge_session, sort_wakeups

KEY = 'GH13-20260819-184158'

def state(tmp_path):
    ...

def gh(gh_with_no_posts):
    ...

def ran(state, number: int, cause: Cause, status: int | None) -> None:
    ...

def found(state) -> Wakeup | WaitingSession | None:
    ...

def test_a_session_that_has_run_no_round_at_all_waits_for_a_person(state):
    ...

def test_a_session_whose_last_round_was_interrupted_is_carried_on(state):
    ...

def test_a_session_whose_last_round_failed_is_carried_on_with_its_status(state):
    ...

def test_a_round_that_did_not_finish_is_carried_on_before_github_is_asked(state, gh):
    ...

def test_a_session_nobody_has_posted_on_needs_nothing(state, gh):
    ...

def test_a_session_the_user_has_posted_on_answers_what_they_said(state, gh):
    ...

def test_a_batch_of_posts_says_how_many_it_holds(state, gh):
    ...

def test_a_post_the_session_has_been_told_about_already_wakes_nothing(state, gh):
    ...

def test_the_prompt_of_a_posts_resume_sends_the_session_to_the_next_rounds_inbox(state, gh):
    ...

def test_a_pull_request_that_is_finished_calls_for_one_last_round(state, gh, state_name):
    ...

def test_a_last_round_carries_what_the_user_said_before_the_merge(state, gh):
    ...

def test_a_session_whose_last_round_wound_it_up_needs_nothing(state, gh):
    ...

def test_a_last_round_that_was_carried_on_is_still_the_last_round(state, gh):
    ...

def test_a_session_with_no_pull_request_of_its_own_waits_for_a_person(state, gh):
    ...

def test_an_open_pull_request_outranks_the_ones_that_are_finished(state, gh):
    ...

def test_the_newest_of_two_finished_pull_requests_is_the_sessions_own(state, gh):
    ...

def test_a_pull_request_read_that_failed_leaves_the_session_waiting(state, gh):
    ...

def test_a_peek_that_failed_leaves_the_session_waiting(state, gh):
    ...

def test_the_most_open_work_comes_first(state):
    ...
