# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_harnesses.py

from dreamcatcher.claude import CLAUDE
from dreamcatcher.codex import CODEX
from dreamcatcher.config import Harness
from dreamcatcher.harnesses import ADAPTERS

def test_every_harness_the_config_names_is_run_by_its_own_adapter():
    ...
