# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_prompts.py

import pytest
from conftest import CONFIG
from dreamcatcher.config import CONFIG_NAME, Harness, read_config
from dreamcatcher.prompts import POSTSCRIPT, compose_first_round_prompt

OPENINGS = {Harness.CLAUDE: '/dream:smith GH12', Harness.CODEX: '$dream:smith GH12'}

def test_a_template_holding_other_words_in_braces_keeps_them():
    ...

def test_the_prompt_that_opens_a_session_is_its_template_then_the_postscript(tmp_path, harness):
    ...
