# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_feed.py

from datetime import UTC, datetime, timedelta, timezone
from pathlib import PurePosixPath, PureWindowsPath
from clocks import PINNED, Ticking
from dreamcatcher.feed import WIDTH, Note, Prose, Renderer

WORKTREE = PurePosixPath('/checkout/worktree')

def feed() -> Renderer:
    ...

def test_a_note_becomes_one_timestamped_line():
    ...

def test_a_note_with_nothing_to_add_is_its_label_alone():
    ...

def test_a_detail_loses_the_worktrees_own_path():
    ...

def test_a_path_outside_the_worktree_keeps_its_own_root():
    ...

def test_a_sibling_of_the_worktree_that_starts_the_same_way_keeps_its_path():
    ...

def test_a_detail_written_the_windows_way_loses_the_worktree_too():
    ...

def test_a_detail_spread_over_lines_becomes_one():
    ...

def test_a_detail_longer_than_the_feed_is_clipped():
    ...

def test_prose_becomes_a_line_for_each_line_it_holds():
    ...

def test_prose_with_nothing_in_it_writes_nothing():
    ...

def test_a_subagents_lines_are_indented_under_the_timestamp():
    ...

def test_a_round_opens_with_its_number_and_its_cause():
    ...

def test_a_clock_that_is_not_in_utc_still_stamps_utc():
    ...

def test_the_clock_a_renderer_reads_by_default_is_the_time_now_in_utc():
    ...
