# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_github_integration.py

from pathlib import Path
import pytest
from dreamcatcher.github import PullRequest, PullRequestState, blockers, identify, issues, login, pull_request

pytestmark = pytest.mark.integration
REPOSITORY = 'alimanfoo/dreamcatcher'
CHECKOUT = Path(__file__).parent.parent
MERGED = 25
MERGED_BRANCH = 'dream-catcher-GH7-20260819-184158'
BLOCKED = 9
BLOCKING = 8

def test_this_checkout_is_this_repository():
    ...

def test_gh_is_signed_in_as_somebody():
    ...

def test_the_dispatch_label_lists_the_issues_it_carries():
    ...

def test_a_merged_pull_request_comes_back_merged():
    ...

def test_a_branch_that_never_existed_has_no_pull_request():
    ...

def test_a_blocked_issue_names_what_blocks_it():
    ...
