# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_sessions.py

import pytest
from clocks import PINNED
from conftest import CONFIG, commit, git
from dreamcatcher.commands import CommandError
from dreamcatcher.config import CONFIG_NAME, Harness, read_config
from dreamcatcher.errors import ReportableError
from dreamcatcher.sessions import Session, create_session
from dreamcatcher.state import StateDirectory

KEY = 'GH12-20260819-184158'
BRANCH = f'dreamcatcher-{KEY}'

def checkout(cloned):
    ...

def state(checkout):
    ...

def mapping(checkout):
    ...

def written(state):
    ...

def test_a_session_cuts_a_worktree_of_its_own_under_the_state_directory(state, mapping):
    ...

def test_a_session_cuts_a_branch_of_its_own_from_origins_main_as_it_is_now(state, mapping):
    ...

def test_a_session_records_what_it_was_dispatched_with(state, mapping):
    ...

def test_a_session_runs_on_the_harness_the_run_named(state, mapping):
    ...

def test_a_session_git_cannot_cut_leaves_no_branch_behind(state, mapping):
    ...

def test_a_session_that_cannot_record_leaves_no_worktree_and_no_branch(state, mapping):
    ...
