# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_recordings.py

from pathlib import PurePosixPath
import pytest
from clocks import Ticking
from recordings import FIXTURES, rendered
from dreamcatcher.claude import CLAUDE
from dreamcatcher.codex import CODEX
from dreamcatcher.feed import Renderer

RECORDED_IN = PurePosixPath('/private/tmp/dreamcatcher-recording')
RECORDINGS = ((CLAUDE, 'claude'), (CODEX, 'codex'))

def test_a_recorded_stream_renders_as_its_golden_feed(adapter, recording):
    ...
