# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_documents.py

from pathlib import Path
import pytest
from dreamcatcher.documents import Document, read_toml
from dreamcatcher.errors import ReportableError

def write(path: Path, text: str) -> Path:
    ...

def test_a_valid_document_reads_back(tmp_path):
    ...

def test_a_missing_document_names_the_path(tmp_path):
    ...

def test_an_unreadable_document_says_so(tmp_path):
    ...

def test_a_document_that_is_not_toml_says_so(tmp_path):
    ...

def test_a_document_that_is_not_utf_8_says_so(tmp_path):
    ...

def test_a_document_that_breaks_its_model_lists_every_fault(tmp_path):
    ...

class Sample(Document):
    name: str
    count: int = 1
