# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_state.py

import pytest
from conftest import git
from dreamcatcher.errors import ReportableError
from dreamcatcher.state import StateDirectory

def test_bootstrap_creates_a_directory_that_ignores_itself(repo):
    ...

def test_bootstrap_heals_a_deleted_gitignore(repo):
    ...

def test_bootstrap_says_so_when_a_file_sits_where_the_directory_goes(repo):
    ...

def test_the_daemon_files_sit_in_the_state_directory(tmp_path):
    ...
