# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_daemon.py

import json
import os
import sys
from contextlib import suppress
import psutil
import pytest
from clocks import PINNED, Ticking
from conftest import CONFIG_HEAD, FILED, LABEL, LATER, REPOSITORY, SMITH_CLAUDE, SMITH_CODEX, git, gone, listing
from fakes import Line
from records import write_round, write_session
from dreamcatcher.commands import spawn
from dreamcatcher.config import CONFIG_NAME, Harness
from dreamcatcher.daemon import Daemon
from dreamcatcher.errors import ReportableError
from dreamcatcher.rounds import Cause, Ending, RoundRecord
from dreamcatcher.state import CandidateIssue, LastTick, StateDirectory, Waiting

KEY = 'GH13-20260819-184158'
CAUSE = Cause.DISPATCH
STILL_RUNNING = 30
DISPATCHED_KEY = 'GH8-20260819-184158'

def left_running(tmp_path):
    ...

def alone(fake, stand_ins, monkeypatch):
    ...

def idling(root, ticks: int) -> tuple[Daemon, Interrupting, Ticking]:
    ...

def settling(root, ticks: int) -> Daemon:
    ...

def test_the_daemon_ticks_on_the_interval_until_the_user_interrupts(watched, harnesses, gh):
    ...

def test_every_tick_records_when_it_ran(watched, harnesses, gh):
    ...

def test_the_daemon_bootstraps_the_state_directory_and_releases_the_lock(watched, harnesses, gh):
    ...

def test_a_second_daemon_refuses_while_the_first_holds_the_repo(watched, harnesses, gh):
    ...

def test_the_daemon_runs_the_harness_it_was_given(watched):
    ...

def test_a_checkout_with_no_config_names_the_file_it_needs(repo):
    ...

def test_a_directory_that_is_not_a_repository_is_refused(tmp_path):
    ...

def test_a_linked_worktree_is_refused(tmp_path):
    ...

def test_the_state_directory_sits_in_the_checkout(watched):
    ...

def test_a_run_refuses_when_a_harness_it_could_dispatch_to_is_not_installed(watched, alone):
    ...

def test_a_run_refuses_when_the_harness_it_was_named_is_not_installed(repo, alone):
    ...

def test_a_round_the_daemon_before_this_one_left_running_is_ended(watched, harnesses, gh, left_running):
    ...

def test_a_round_that_recorded_an_ending_is_left_running_by_the_sweep(watched, harnesses, gh, left_running):
    ...

def configure(root, head: str) -> None:
    ...

def held(daemon) -> str:
    ...

def recorded(daemon) -> LastTick:
    ...

def gh(fake):
    ...

def offered(gh):
    ...

def dispatching(cloned, offered, harnesses):
    ...

def test_a_tick_dispatches_the_oldest_issue_nothing_stands_in_the_way_of(dispatching, harnesses):
    ...

def test_a_dispatched_round_records_what_caused_it_and_what_it_said(dispatching):
    ...

def test_a_tick_launches_one_round_and_leaves_the_rest_in_the_queue(dispatching, offered):
    ...

def test_a_second_tick_judges_a_dispatched_issue_handled(dispatching):
    ...

def test_a_tick_at_the_cap_spends_no_github_call(dispatching, offered, harnesses):
    ...

def test_a_tick_with_nothing_eligible_dispatches_nothing(dispatching, offered):
    ...

def test_a_tick_whose_listing_failed_records_what_it_could_not_read(dispatching, offered):
    ...

def test_a_tick_that_could_not_dispatch_records_the_failure_and_ticks_again(dispatching):
    ...

def test_a_run_that_cannot_be_told_which_repository_this_is_refuses(cloned, gh, harnesses):
    ...

def test_the_daemon_ends_the_rounds_it_holds_as_it_goes_down(dispatching, harnesses):
    ...

def test_a_round_that_failed_lately_holds_every_launch(dispatching):
    ...

def test_a_round_that_failed_long_enough_ago_holds_nothing(dispatching):
    ...

def test_a_round_that_ended_well_holds_nothing(dispatching):
    ...

def test_a_session_whose_last_round_was_interrupted_reads_as_waiting(dispatching, left_running):
    ...

def test_a_session_whose_last_round_failed_reads_as_waiting_with_its_status(dispatching):
    ...

def test_a_session_the_daemon_is_running_a_round_for_is_not_waiting(dispatching, harnesses):
    ...

def test_a_session_whose_last_round_ended_well_is_not_waiting(dispatching):
    ...

def test_a_session_that_has_run_no_round_at_all_waits_for_its_first(dispatching):
    ...

def test_a_dispatch_whose_round_will_not_start_leaves_no_session_behind(dispatching):
    ...

def test_a_run_that_cannot_read_a_session_refuses_to_start(dispatching):
    ...

def test_a_session_that_goes_bad_under_a_running_daemon_costs_one_tick(dispatching):
    ...

class Interrupting:
    def __init__(self, ticks: int, settle) -> None:
        ...

    def __call__(self, seconds: float) -> None:
        ...
