# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_git.py

from pathlib import Path
import pytest
from conftest import git
from dreamcatcher.commands import CommandError
from dreamcatcher.git import add_worktree, delete_branch, fetch, remove_worktree

BRANCH = 'dreamcatcher-GH8-20260820-000456'

def session_worktree(*, root):
    ...

def worktrees(*, root):
    ...

def test_a_fetch_brings_origins_main_back(cloned):
    ...

def test_a_worktree_lands_where_it_is_asked_for_on_its_own_branch(cloned):
    ...

def test_a_worktree_git_refuses_says_what_git_said(cloned):
    ...

def test_a_removed_worktree_leaves_the_disk_and_the_list(cloned):
    ...

def test_removing_a_worktree_that_was_never_made_says_what_git_said(cloned):
    ...

def test_a_deleted_branch_leaves_the_branch_list(cloned):
    ...

def test_a_branch_a_worktree_holds_is_not_deleted_quietly(cloned):
    ...
