# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_rounds.py

from typing import cast
import pytest
from clocks import PINNED
from conftest import FIXTURES
from fakes import Line, Stream, recorded
from recordings import rendered
from dreamcatcher.adapters import Adapter, Launch
from dreamcatcher.claude import CLAUDE
from dreamcatcher.errors import ReportableError
from dreamcatcher.feed import Event, Note, Renderer
from dreamcatcher.rounds import Round, RoundRecord

RECORDING = FIXTURES / 'claude' / 'round.jsonl'
STAMP = '2026-08-19T18:41:58Z'

def pinned():
    ...

def worktree(tmp_path):
    ...

def directory(tmp_path):
    ...

def written(path):
    ...

def test_a_round_runs_the_command_it_was_given_in_the_worktree(fake, worktree, directory):
    ...

def test_the_feed_a_round_writes_is_the_feed_its_stream_renders_as(fake, worktree, directory):
    ...

def test_a_round_keeps_the_harnesss_own_stream_as_it_arrived(fake, worktree, directory):
    ...

def test_what_the_harness_says_on_stderr_lands_where_it_happened(fake, worktree, directory):
    ...

def test_a_line_the_feed_cannot_write_costs_that_line_alone(fake, worktree, directory):
    ...

def test_a_round_says_when_it_started_and_what_process_it_is(fake, worktree, directory):
    ...

def test_a_round_that_finished_says_how_it_ended(fake, worktree, directory):
    ...

def test_a_round_somebody_stopped_says_no_ending(fake, worktree, directory):
    ...

def test_a_round_that_cannot_write_its_feed_stops_rather_than_stalls(fake, worktree, directory):
    ...

def test_a_round_that_cannot_record_its_start_does_not_run_on(fake, worktree, tmp_path):
    ...

class Unrenderable(Adapter):
    program = 'harness'

    def first_round(self, launch: Launch) -> list[str]:
        ...

    def resume(self, launch: Launch) -> list[str]:
        ...

    def _events(self, streamed: dict) -> list[Event]:
        ...
