# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_github.py

import json
from datetime import UTC, datetime
from pathlib import Path
import pytest
from conftest import POST_LIST_PATHS, POSTED_BY, PULL_REQUEST, pages
from dreamcatcher.github import AnyPost, Blocker, BlockerState, Comment, InlineComment, Issue, LinkedPullRequest, PullRequest, PullRequestState, Review, Unknown, Verdict, identify_account, identify_repository, list_blockers, list_issues, list_linked_pull_requests, list_posts, list_pull_requests

REPOSITORY = 'alimanfoo/dreamcatcher'
BRANCH = 'dreamcatcher-GH8-20260820-000456'
COMMENT = {'id': 1, 'user': {'login': POSTED_BY}, 'created_at': '2026-09-03T16:49:35Z'}
REVIEW = {'id': 2, 'state': 'COMMENTED', 'submitted_at': '2026-09-03T22:27:20Z'}
INLINE_COMMENT = ...

def test_the_repository_comes_from_the_checkouts_own_remote(fake, tmp_path):
    ...

def test_the_signed_in_account_is_the_one_gh_names(fake):
    ...

def test_a_listing_carries_each_issue_and_when_it_was_filed(fake):
    ...

def test_the_pull_requests_of_a_branch_come_back_with_their_states(fake):
    ...

def test_a_branch_with_no_pull_request_comes_back_empty(fake):
    ...

def test_the_pull_requests_linked_to_an_issue_come_back(fake):
    ...

def test_an_issue_nobody_has_claimed_has_no_linked_pull_request(fake):
    ...

def test_the_blockers_of_an_issue_come_back_with_their_states(fake):
    ...

def posted() -> list[AnyPost]:
    ...

def test_a_pull_request_nobody_has_posted_on_comes_back_with_no_posts(gh_with_no_posts):
    ...

def test_the_posts_of_a_pull_request_come_from_all_three_of_its_lists(gh_with_no_posts):
    ...

def test_each_of_the_three_lists_is_read_whole(gh_with_no_posts):
    ...

def test_the_pages_of_one_list_come_back_as_one_list(gh_with_no_posts):
    ...

def test_a_post_that_is_not_a_document_at_all_is_unknown(gh_with_no_posts):
    ...

def test_every_post_a_real_pull_request_carries_reads_back(gh_with_recorded_posts):
    ...

def test_a_recorded_comment_reads_back_as_the_user_wrote_it(gh_with_recorded_posts):
    ...

def test_a_recorded_review_reads_back_when_it_was_submitted_and_its_verdict(gh_with_recorded_posts):
    ...

def test_the_reviews_github_wrapped_the_inline_comments_in_say_nothing(gh_with_recorded_posts):
    ...

def test_a_recorded_inline_comment_reads_the_line_it_was_written_against(gh_with_recorded_posts):
    ...

def test_a_recorded_inline_comment_carries_the_diff_it_was_written_against(gh_with_recorded_posts):
    ...

def test_a_read_that_fails_answers_unknown_with_what_gh_said(fake, ask):
    ...

def test_a_read_gh_answers_strangely_is_unknown_too(fake):
    ...
