# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_recordings.py

from pathlib import Path, PurePosixPath
import pytest
from clocks import Ticking
from dreamcatcher.claude import CLAUDE
from dreamcatcher.feed import Renderer

FIXTURES = Path(__file__).parent / 'fixtures' / 'claude'
RECORDED_IN = PurePosixPath('/private/tmp/dreamcatcher-recording')

def rendered(recording: Path) -> str:
    ...

def test_a_recorded_stream_renders_as_its_golden_feed(recording):
    ...
