# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_github_integration.py

from pathlib import Path
import pytest
from dreamcatcher.github import PullRequest, PullRequestState, identify_account, identify_repository, list_blockers, list_issues, list_linked_pull_requests, list_pull_requests

pytestmark = pytest.mark.integration
REPOSITORY = 'alimanfoo/dreamcatcher'
CHECKOUT = Path(__file__).parent.parent
MERGED = 25
MERGED_BRANCH = 'dream-catcher-GH7-20260819-184158'
BLOCKED = 9
BLOCKING = 8

def test_this_checkout_is_this_repository():
    ...

def test_gh_is_signed_in_as_somebody():
    ...

def test_gh_takes_the_whole_issue_listing_command():
    ...

def test_a_merged_pull_request_comes_back_merged():
    ...

def test_a_branch_that_never_existed_comes_back_empty():
    ...

def test_gh_takes_the_linked_pull_requests_command():
    ...

def test_a_blocked_issue_names_what_blocks_it():
    ...
