# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_feed.py

from datetime import timedelta, timezone
from pathlib import PurePosixPath
from clocks import PINNED, Ticking
from dreamcatcher.feed import WIDTH, Note, Prose, Renderer

ROUND = PurePosixPath('/checkout/worktree')

def feed() -> Renderer:
    ...

def test_a_note_becomes_one_timestamped_line():
    ...

def test_a_note_with_nothing_to_add_is_its_label_alone():
    ...

def test_a_detail_loses_the_rounds_own_directory():
    ...

def test_a_path_outside_the_round_keeps_its_own_root():
    ...

def test_a_detail_spread_over_lines_becomes_one():
    ...

def test_a_detail_longer_than_the_feed_is_clipped():
    ...

def test_prose_becomes_a_line_for_each_line_it_holds():
    ...

def test_prose_with_nothing_in_it_writes_nothing():
    ...

def test_a_subagents_lines_are_indented_under_the_timestamp():
    ...

def test_a_round_opens_with_its_number_and_its_cause():
    ...

def test_a_clock_that_is_not_in_utc_still_stamps_utc():
    ...
