# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_git.py

import pytest
from conftest import git
from dreamcatcher.commands import CommandError
from dreamcatcher.git import add_worktree, discard_worktree, fetch

BRANCH = 'dreamcatcher-GH8-20260820-000456'

def session_worktree(root):
    ...

def test_a_fetch_brings_origins_main_back(cloned):
    ...

def test_a_worktree_lands_where_it_is_asked_for_on_its_own_branch(cloned):
    ...

def test_a_worktree_git_refuses_says_what_git_said(cloned):
    ...

def test_discarding_a_worktree_takes_its_branch_with_it(cloned):
    ...

def test_discarding_what_was_never_made_leaves_no_complaint(cloned):
    ...
