# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_config.py

from pathlib import Path
import pytest
from conftest import CONFIG, CONFIG_HEAD, SMITH_CLAUDE, SMITH_CODEX
from dreamcatcher.config import CONFIG_NAME, Harness, HarnessSettings, read_config
from dreamcatcher.errors import ReportableError

WITHOUT_CODEX = CONFIG_HEAD + SMITH_CLAUDE
CLAUDE_SETTINGS = ...
CODEX_SETTINGS = ...

def write_config(root: Path, text: str) -> None:
    ...

def test_a_valid_config_reads_back(tmp_path):
    ...

def test_the_settings_the_design_gives_defaults_for_have_them(tmp_path):
    ...

def test_a_setting_the_config_names_beats_its_default(tmp_path):
    ...

def test_a_label_one_harness_can_run_carries_that_block_alone(tmp_path):
    ...

def test_a_config_mistake_names_the_setting_and_the_fault(tmp_path, mistake, text, fault):
    ...

def test_a_setting_a_harness_cannot_be_given_names_itself(tmp_path, setting):
    ...

def test_a_repo_with_no_config_says_which_file_is_missing(tmp_path):
    ...
