# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_board.py

import os
from datetime import timedelta
import pytest
from clocks import PINNED
from records import write_feed, write_round, write_session, write_tick
from dreamcatcher.board import SessionStanding, read_board, read_rows_for_issue
from dreamcatcher.feed import Line
from dreamcatcher.rounds import Cause, Ending, RoundRecord
from dreamcatcher.state import NO_ROUND_HAS_RUN, CandidateIssue, LastTick, StateDirectory, WaitingSession

KEY = 'GH13-20260819-184158'
LOOKED_AT = PINNED + timedelta(hours=2)
LABEL = 'dream:smith'

def state(tmp_path):
    ...

def running(state):
    ...

def ran(state, number: int, cause: Cause, status: int | None):
    ...

def said(state, number: int, *texts: str):
    ...

def looked(state):
    ...

def only(state):
    ...

def rows_at(state, issue: int):
    ...

def test_the_rows_for_an_issue_are_its_own_sessions_newest_first(running):
    ...

def test_an_issue_no_session_here_has_holds_no_rows(state):
    ...

def test_a_look_at_one_issue_leaves_another_session_s_feed_unread(running):
    ...

def test_a_state_directory_nothing_has_run_in_yet_holds_an_empty_board(tmp_path):
    ...

def test_the_daemon_holding_the_repo_is_the_one_the_lock_names(running):
    ...

def test_a_round_a_running_daemon_has_not_ended_is_the_agent_working(running):
    ...

def test_a_running_round_that_has_said_nothing_yet_says_that(running):
    ...

def test_a_round_with_no_daemon_left_to_run_it_is_waiting(state):
    ...

def test_a_round_that_failed_waits_with_the_status_it_failed_with(running):
    ...

def test_a_session_whose_final_round_has_run_is_done(state):
    ...

def test_a_session_done_in_one_round_counts_that_round_as_one(state):
    ...

def test_a_session_the_tick_found_nothing_to_do_for_needs_you(state):
    ...

def test_a_session_that_wrote_no_feed_at_all_is_idle_for_who_knows_how_long(state):
    ...

def test_a_session_the_tick_left_waiting_says_what_it_waits_on(state):
    ...

def test_a_stuck_session_says_where_to_read_what_it_did(state):
    ...

def test_a_stuck_session_that_ran_no_round_has_no_feed_to_point_at(state):
    ...

def test_a_session_no_tick_has_weighed_and_no_round_has_run_is_stuck(state):
    ...

def test_the_sessions_at_one_issue_read_as_sessions_newest_first(state):
    ...

def test_the_work_that_is_done_reads_most_recent_first(state):
    ...

def test_the_sessions_in_one_standing_come_back_in_the_boards_own_order(state):
    ...

def test_the_queue_reads_each_issues_turn_off_its_place(state):
    ...

def test_an_issue_a_session_here_already_claims_is_not_queued(state):
    ...
