# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_state.py

from conftest import git
from dreamcatcher.state import StateDirectory

def test_bootstrap_creates_a_directory_that_ignores_itself(repo):
    ...

def test_bootstrap_heals_a_deleted_gitignore(repo):
    ...

def test_the_daemon_files_sit_in_the_state_directory(tmp_path):
    ...
