# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_daemon.py

import os
import pytest
from clocks import Ticking
from dreamcatcher.config import CONFIG_NAME, Harness
from dreamcatcher.daemon import Daemon
from dreamcatcher.errors import ReportableError
from dreamcatcher.state import LastTick, StateDirectory

def idling(root, ticks: int) -> tuple[Daemon, Waiting, Ticking]:
    ...

def test_the_daemon_ticks_on_the_interval_until_the_user_interrupts(watched):
    ...

def test_every_tick_records_when_it_ran(watched):
    ...

def test_the_daemon_bootstraps_the_state_directory_and_releases_the_lock(watched):
    ...

def test_a_second_daemon_refuses_while_the_first_holds_the_repo(watched):
    ...

def test_the_daemon_runs_the_harness_it_was_given(watched):
    ...

def test_a_checkout_with_no_config_names_the_file_it_needs(repo):
    ...

def test_a_directory_that_is_not_a_repository_is_refused(tmp_path):
    ...

def test_a_linked_worktree_is_refused(tmp_path):
    ...

def test_the_state_directory_sits_in_the_checkout(watched):
    ...

class Waiting:
    def __init__(self, ticks: int) -> None:
        ...

    def __call__(self, seconds: float) -> None:
        ...
