# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_cli.py

import os
from datetime import timedelta
from importlib.metadata import version
import pytest
from clocks import PINNED
from records import write_feed, write_round, write_session
from dreamcatcher.cli import main
from dreamcatcher.config import Harness
from dreamcatcher.daemon import Daemon
from dreamcatcher.documents import write_text
from dreamcatcher.feed import Line
from dreamcatcher.rounds import Cause, Ending, RoundRecord
from dreamcatcher.state import StateDirectory

def watching(tmp_path):
    ...

def started(monkeypatch):
    ...

def test_version_prints_the_installed_version(capsys):
    ...

def test_a_checkout_no_daemon_has_watched_has_nothing_to_show(monkeypatch, tmp_path, capsys):
    ...

def test_scry_shows_the_board(monkeypatch, watching, capsys):
    ...

def test_scry_naming_an_issue_shows_that_sessions_view(monkeypatch, watching, capsys):
    ...

def test_an_issue_reads_however_the_reader_wrote_it(monkeypatch, watching, capsys):
    ...

def test_something_that_is_not_an_issue_reference_is_refused(capsys):
    ...

def test_scry_following_an_issue_shows_its_feed(monkeypatch, watching, capsys):
    ...

def test_scry_naming_a_round_shows_that_rounds_feed(monkeypatch, watching, capsys):
    ...

def test_a_feed_view_with_no_issue_to_show_asks_for_one(capsys):
    ...

def test_a_feed_reads_as_it_arrives_or_as_it_stands_and_never_as_both(capsys):
    ...

def test_a_bare_invocation_asks_for_a_verb(capsys):
    ...

def test_run_starts_a_daemon_on_the_current_directory(monkeypatch, watched, started):
    ...

def test_the_harness_flag_says_what_to_run_rounds_with(monkeypatch, watched, started):
    ...

def test_a_run_with_no_harness_asks_for_one(capsys):
    ...

def test_a_harness_that_does_not_exist_is_refused(capsys):
    ...

def test_a_failure_the_user_must_read_is_a_message_not_a_traceback(monkeypatch, tmp_path, capsys):
    ...

def test_a_write_the_daemon_cannot_make_is_a_message_not_a_traceback(monkeypatch, watched, capsys, harnesses):
    ...
