# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_commands.py

import pytest
from dreamcatcher.commands import CommandError, run

def test_a_command_hands_back_what_it_printed(fake):
    ...

def test_a_command_runs_where_it_is_told(fake, tmp_path):
    ...

def test_a_program_that_is_not_on_the_path_says_so():
    ...

def test_a_failure_carries_the_command_and_what_it_said(fake):
    ...

def test_a_failure_that_said_nothing_still_names_the_command(fake):
    ...
