# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_codex.py

from conftest import streamed
from dreamcatcher.adapters import Launch
from dreamcatcher.codex import CODEX
from dreamcatcher.feed import Note, Prose

LAUNCH = ...
SETTINGS = ['--model', 'gpt-5.6-sol', '-c', 'model_reasoning_effort="xhigh"']

def completed(**item) -> str:
    ...

def test_a_first_round_runs_where_it_is_launched_under_codexs_own_reviewer():
    ...

def test_a_resume_replays_the_settings_and_the_permissions_codex_forgets():
    ...

def test_the_first_event_names_the_session():
    ...

def test_what_the_agent_says_comes_through_whole():
    ...

def test_a_command_that_ran_reports_what_it_was():
    ...

def test_a_command_that_failed_reports_what_it_said():
    ...

def test_a_command_the_reviewer_declined_reads_as_declined():
    ...

def test_a_patch_reports_each_file_it_touched_as_what_it_did_to_it():
    ...

def test_a_web_search_reports_what_it_looked_for():
    ...

def test_an_error_the_round_survived_reads_as_an_error_not_a_failure():
    ...

def test_a_round_that_ended_well_says_what_it_spent():
    ...

def test_a_round_that_failed_closes_with_what_went_wrong():
    ...

def test_an_event_the_feed_has_no_line_for_writes_nothing():
    ...

def test_a_line_that_is_not_json_comes_through_unchanged():
    ...

def test_a_line_of_json_that_is_not_an_event_comes_through_unchanged():
    ...

def test_an_event_shaped_in_a_way_the_parser_cannot_read_comes_through_unchanged():
    ...

def test_an_item_that_is_not_a_mapping_comes_through_unchanged():
    ...
