# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_eligibility.py

import json
import pytest
from dreamcatcher.config import Config
from dreamcatcher.eligibility import judge_issues
from dreamcatcher.github import Unknown
from dreamcatcher.state import Candidate

REPOSITORY = 'alimanfoo/dreamcatcher'
FILED = '2026-08-19T18:41:58Z'
LATER = '2026-08-20T09:00:00Z'
SETTINGS = {'prompt': '/dream:smith GH{issue}', 'model': 'opus[1m]', 'effort': 'xhigh'}

def mapping(*labels: str) -> Config:
    ...

def listing(*issues: tuple[int, str]) -> str:
    ...

def gh(fake):
    ...

def weighed(config, claimed):
    ...

def test_an_issue_nothing_stands_in_the_way_of_can_be_dispatched(gh):
    ...

def test_the_issues_come_back_oldest_first(gh):
    ...

def test_a_listing_the_tool_cannot_read_answers_unknown_for_the_whole_tick(gh):
    ...

def test_an_issue_carrying_more_than_one_mapped_label_is_skipped(gh):
    ...

def test_an_issue_a_session_of_this_run_is_working_on_is_left_alone(gh):
    ...

def test_an_issue_with_a_pull_request_open_on_it_is_left_alone(gh):
    ...

def test_a_pull_request_read_that_failed_reads_as_claimed(gh):
    ...

def test_an_issue_an_open_issue_blocks_names_what_blocks_it(gh):
    ...

def test_a_blocker_read_that_failed_reads_as_blocked(gh):
    ...
