# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_tui.py

from datetime import timedelta
from io import StringIO
import psutil
import pytest
from clocks import PINNED
from conftest import FIXTURES, LABEL
from records import write_feed, write_round, write_session, write_tick
from rich.console import Console
from rich.text import Text
from dreamcatcher.documents import append_text, write_text
from dreamcatcher.errors import ReportableError
from dreamcatcher.feed import Line
from dreamcatcher.rounds import Cause, Ending, RoundRecord
from dreamcatcher.state import NO_ROUND_HAS_RUN, CandidateIssue, LastTick, StateDirectory, WaitingSession
from dreamcatcher.tui import PAUSE, _paint, _paint_written, render_board, render_session, show_board, show_feed, show_session

LOOKED_AT = PINNED + timedelta(hours=2)
WIDTH = 100
DAEMON_PID = 4242
STAMP = '20260819-184158'
SAID = ...
DOUBLE_LABELLED = 'carries more than one mapped label: dream:less, dream:smith'
BOARDS = ...
FEEDS = ...
SESSIONS = ...

def daemon(monkeypatch):
    ...

def written(state, issue: int, *records: RoundRecord):
    ...

def ended(minute: int, status: int, cause: Cause):
    ...

def running(minute: int, cause: Cause):
    ...

def holding(state):
    ...

def fabricate_nothing(state):
    ...

def fabricate_everything(state):
    ...

def fabricate_a_dead_daemon(state):
    ...

def fabricate_the_cap(state):
    ...

def fabricate_repeat_sessions(state):
    ...

def fabricate_a_silent_round(state):
    ...

def pinned(written_to, width: int, is_terminal: bool) -> Console:
    ...

def interrupting(seconds):
    ...

def rendered(state, width: int) -> str:
    ...

def test_a_state_directory_renders_as_its_golden_board(name, tmp_path, daemon):
    ...

def test_showing_the_board_prints_the_board_it_built(tmp_path, daemon):
    ...

def test_a_key_too_wide_for_the_console_folds_rather_than_being_cut(tmp_path):
    ...

def viewed(state, issue: int, width: int) -> str:
    ...

def test_wrapped_latest_output_keeps_its_indent(tmp_path, daemon):
    ...

def test_showing_a_session_prints_the_session_view_it_built(tmp_path, daemon):
    ...

def test_a_session_renders_as_its_golden_view(name, tmp_path, daemon):
    ...

def followed(state, issue: int, wait) -> str:
    ...

def test_a_feed_nobody_is_watching_shows_what_is_there_and_returns(tmp_path, daemon):
    ...

def test_a_feed_renders_as_its_golden_view(name, tmp_path, daemon):
    ...

def test_only_a_feed_lines_stamp_is_dim():
    ...

def test_a_following_view_waits_for_the_round_a_session_has_yet_to_run(tmp_path, daemon):
    ...

def test_a_following_view_looks_once_more_when_the_last_round_stops(tmp_path, daemon):
    ...

def test_a_round_that_starts_while_the_view_is_going_arrives_in_it(tmp_path, daemon):
    ...

def test_a_view_of_a_session_that_is_over_never_waits(tmp_path, daemon):
    ...

def test_a_following_view_waits_for_the_next_daemon(tmp_path):
    ...

def test_a_view_of_a_stuck_session_never_waits(tmp_path, daemon):
    ...

def test_a_following_view_reads_a_round_on_from_where_it_stopped(tmp_path, daemon):
    ...

def test_a_write_that_never_landed_waits_for_the_look_that_shows_it_whole(tmp_path, daemon):
    ...

def test_a_line_the_view_cannot_read_reaches_the_reader_as_it_was_written(tmp_path, daemon):
    ...

def test_a_reader_who_has_seen_enough_interrupts_the_view(tmp_path, daemon):
    ...

def viewed_round(state, issue: int, number: int, wait) -> str:
    ...

def test_one_round_of_a_session_reads_on_its_own(tmp_path, daemon):
    ...

def test_a_round_that_wrote_no_feed_shows_the_line_that_opens_it(tmp_path, daemon):
    ...

def test_a_view_of_one_round_shows_it_as_it_stands(tmp_path, daemon):
    ...

def test_a_round_the_session_never_ran_says_how_many_it_did(tmp_path, daemon):
    ...

def test_an_issue_no_session_here_has_says_so(tmp_path):
    ...
