# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_prompts.py

import pytest
from conftest import CONFIG, FIXTURES
from dreamcatcher.config import CONFIG_NAME, Harness, read_config
from dreamcatcher.prompts import first_round

PROMPTS = FIXTURES / 'prompts'

def test_the_issues_number_replaces_the_word_the_template_holds_for_it():
    ...

def test_a_template_holding_other_words_in_braces_keeps_them():
    ...

def test_the_prompt_that_opens_a_session_reads_as_its_golden(tmp_path, harness):
    ...
