# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_fakes.py

from time import perf_counter
import pytest
from dreamcatcher.commands import CommandError, run

STREAM = '{"type":"assistant","text":"café"}\n{"type":"result"}\n'

def recording(tmp_path):
    ...

def test_a_stand_in_harness_replays_the_recording_it_was_given(fake, recording):
    ...

def test_a_stand_in_harness_streams_at_the_pace_it_was_given(fake, recording):
    ...

def test_a_stand_in_harness_can_end_as_a_failed_round_does(fake, recording):
    ...

def test_a_stand_in_nobody_scripted_says_so(fake):
    ...
