# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_github.py

import json
from datetime import UTC, datetime
from pathlib import Path
import pytest
from dreamcatcher.github import Blocker, BlockerState, Issue, LinkedPullRequest, PullRequest, PullRequestState, Unknown, blockers, identify, issues, linked_pull_requests, login, pull_requests

REPOSITORY = 'alimanfoo/dreamcatcher'
BRANCH = 'dreamcatcher-GH8-20260820-000456'

def test_the_repository_comes_from_the_checkouts_own_remote(fake, tmp_path):
    ...

def test_the_signed_in_account_is_the_one_gh_names(fake):
    ...

def test_a_listing_carries_each_issue_and_when_it_was_filed(fake):
    ...

def test_the_pull_requests_of_a_branch_come_back_with_their_states(fake):
    ...

def test_a_branch_with_no_pull_request_comes_back_empty(fake):
    ...

def test_the_pull_requests_linked_to_an_issue_come_back(fake):
    ...

def test_an_issue_nobody_has_claimed_has_no_linked_pull_request(fake):
    ...

def test_the_blockers_of_an_issue_come_back_with_their_states(fake):
    ...

def test_a_read_that_fails_answers_unknown_with_what_gh_said(fake, ask):
    ...

def test_a_read_gh_answers_strangely_is_unknown_too(fake):
    ...
