# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_prompts.py

from pathlib import Path
import pytest
from conftest import CONFIG
from dreamcatcher.config import CONFIG_NAME, Harness, read_config
from dreamcatcher.prompts import CARRY_ON_PROMPT, MARKER, POSTSCRIPT, compose_first_round_prompt, compose_inbox_prompt

OPENINGS = {Harness.CLAUDE: '/dream:smith GH12', Harness.CODEX: '$dream:smith GH12'}

def test_a_template_holding_other_words_in_braces_keeps_them():
    ...

def test_the_prompt_that_opens_a_session_is_its_template_then_the_postscript(tmp_path, harness):
    ...

def test_the_prompt_that_carries_a_round_on_says_the_last_one_stopped_short():
    ...

def test_the_prompt_that_hands_over_an_inbox_names_the_pull_request_and_the_file(tmp_path):
    ...

def test_every_prompt_the_daemon_composes_asks_for_the_marker():
    ...
