# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/adapters.py

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import ClassVar
from dreamcatcher.commands import locate
from dreamcatcher.feed import Event

class Launch:
    session: str
    model: str
    effort: str
    prompt: str

class Adapter(ABC):
    program: ClassVar[str]

    def installed(self) -> None:
        ...

    def first_round(self, launch: Launch) -> list[str]:
        ...

    def resume(self, launch: Launch) -> list[str]:
        ...

    def read(self, line: str) -> list[Event]:
        ...
