# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/board.py

from collections.abc import Callable
from dataclasses import dataclass
from datetime import datetime
from enum import StrEnum
from dreamcatcher.clock import describe_span, now
from dreamcatcher.documents import read_json
from dreamcatcher.feed import Line, read_last_feed_line
from dreamcatcher.lock import read_daemon_pid
from dreamcatcher.sessions import Session, read_sessions
from dreamcatcher.state import LastTick, StateDirectory, WaitingSession

NEVER_STARTED = 'its first round never started'

def read_board(state: StateDirectory, clock: Callable[[], datetime]) -> Board:
    ...

def _count_rounds(session: Session) -> str:
    ...

def _when_it_last_ran(attempt: Attempt) -> datetime:
    ...

def _list_queue(tick: LastTick | None, claimed: set[int]) -> list[QueuedIssue]:
    ...

def _describe_place(ahead: int) -> str:
    ...

class Standing(StrEnum):
    NEEDS_YOU = 'needs you'
    WORKING = 'agent working'
    WAITING = 'waiting'
    STUCK = 'stuck'
    DONE = 'done'

class Attempt:
    session: Session
    standing: Standing
    detail: str
    attempt: int
    attempts: int

class QueuedIssue:
    issue: int
    label: str
    reason: str

class Board:
    at: datetime
    daemon_pid: int | None
    tick: LastTick | None
    attempts: list[Attempt]
    queued: list[QueuedIssue]

    def list_standing(self, standing: Standing) -> list[Attempt]:
        ...

class _Look:
    state: StateDirectory
    at: datetime
    daemon_pid: int | None
    waits: dict[str, WaitingSession]

    def list_attempts(self, sessions: list[Session]) -> list[Attempt]:
        ...

    def _read_attempt(self, session: Session, place: int, attempts: int) -> Attempt:
        ...

    def _judge_standing(self, session: Session) -> tuple[Standing, str]:
        ...

    def _judge_wait(self, session: Session) -> tuple[Standing, str]:
        ...

    def _describe_live_round(self, session: Session) -> str:
        ...

    def _describe_idle(self, session: Session) -> str:
        ...

    def _read_last_said(self, session: Session) -> Line | None:
        ...

    def _point_at_feed(self, session: Session, reason: str) -> str:
        ...
