# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/board.py

from collections.abc import Callable
from dataclasses import dataclass
from datetime import datetime
from enum import StrEnum
from dreamcatcher.clock import now
from dreamcatcher.documents import read_json
from dreamcatcher.feed import Line, read_last_feed_line
from dreamcatcher.lock import read_daemon_pid
from dreamcatcher.rounds import RoundRecord
from dreamcatcher.sessions import Session, read_sessions
from dreamcatcher.state import NO_ROUND_HAS_RUN, LastTick, StateDirectory, WaitingSession
from dreamcatcher.words import describe_count, describe_span

def read_board(state: StateDirectory, clock: Callable[[], datetime]) -> Board:
    ...

def read_rows_for_issue(state: StateDirectory, issue: int, clock: Callable[[], datetime]) -> list[SessionRow]:
    ...

def _describe_place_in_queue(ahead: int) -> str:
    ...

class SessionStanding(StrEnum):
    NEEDS_YOU = 'needs you'
    WORKING = 'agent working'
    WAITING = 'waiting'
    STUCK = 'stuck'
    DONE = 'done'

class SessionRow:
    session: Session
    standing: SessionStanding
    detail: str
    last_output: str | None

class QueuedIssue:
    issue: int
    label: str
    reason: str

class Board:
    at: datetime
    daemon_pid: int | None
    tick: LastTick | None
    rows: list[SessionRow]
    queued: list[QueuedIssue]

    def list_rows_for_standing(self, standing: SessionStanding) -> list[SessionRow]:
        ...

class _Look:
    def __init__(self, state: StateDirectory, clock: Callable[[], datetime]) -> None:
        ...

    def compose_board(self, sessions: list[Session]) -> Board:
        ...

    def list_rows(self, sessions: list[Session]) -> list[SessionRow]:
        ...

    def _read_row(self, session: Session) -> SessionRow:
        ...

    def _judge_standing(self, session: Session) -> tuple[SessionStanding, str, str | None]:
        ...

    def _judge_wait(self, session: Session) -> tuple[SessionStanding, str]:
        ...

    def _describe_live_round(self, session: Session, live_round: RoundRecord) -> tuple[str, str | None]:
        ...

    def _describe_idle(self, session: Session) -> str:
        ...

    def _read_last_said(self, session: Session) -> Line | None:
        ...

    def _list_queued_issues(self, claimed: set[int]) -> list[QueuedIssue]:
        ...

    def _point_at_feed(self, session: Session, reason: str) -> str:
        ...
