# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/board.py

from collections.abc import Callable
from dataclasses import dataclass
from datetime import datetime
from enum import StrEnum
from dreamcatcher.clock import now
from dreamcatcher.documents import read_json
from dreamcatcher.feed import Line, read_last_feed_line
from dreamcatcher.lock import read_daemon_pid
from dreamcatcher.sessions import Session, read_sessions
from dreamcatcher.state import NO_ROUND_HAS_RUN, LastTick, StateDirectory, WaitingSession
from dreamcatcher.words import describe_count, describe_span

def read_board(state: StateDirectory, clock: Callable[[], datetime]) -> Board:
    ...

def read_rows(state: StateDirectory, issue: int, clock: Callable[[], datetime]) -> list[Row]:
    ...

def _list_queue(tick: LastTick | None, claimed: set[int]) -> list[QueuedIssue]:
    ...

def _describe_place(ahead: int) -> str:
    ...

class Standing(StrEnum):
    NEEDS_YOU = 'needs you'
    WORKING = 'agent working'
    WAITING = 'waiting'
    STUCK = 'stuck'
    DONE = 'done'

class Row:
    session: Session
    standing: Standing
    detail: str
    last_output: str | None

class QueuedIssue:
    issue: int
    label: str
    reason: str

class Board:
    at: datetime
    daemon_pid: int | None
    tick: LastTick | None
    rows: list[Row]
    queued: list[QueuedIssue]

    def list_standing(self, standing: Standing) -> list[Row]:
        ...

class _Look:
    def __init__(self, state: StateDirectory, clock: Callable[[], datetime]) -> None:
        ...

    def list_rows(self, sessions: list[Session]) -> list[Row]:
        ...

    def _read_row(self, session: Session) -> Row:
        ...

    def _judge_standing(self, session: Session) -> tuple[Standing, str, str | None]:
        ...

    def _judge_wait(self, session: Session) -> tuple[Standing, str]:
        ...

    def _describe_live_round(self, session: Session) -> tuple[str, str | None]:
        ...

    def _describe_idle(self, session: Session) -> str:
        ...

    def _read_last_said(self, session: Session) -> Line | None:
        ...

    def _point_at_feed(self, session: Session, reason: str) -> str:
        ...
