# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/cli.py

import argparse
import sys
from collections.abc import Sequence
from importlib.metadata import version
import dreamcatcher

DEFAULT_VERB = 'run'

def build_parser() -> argparse.ArgumentParser:
    ...

def main(argv: Sequence[str] | None) -> int:
    ...
