# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/cli.py

import argparse
import re
import sys
from collections.abc import Sequence
from importlib.metadata import version
from pathlib import Path
import dreamcatcher
from dreamcatcher import tui
from dreamcatcher.config import Harness
from dreamcatcher.daemon import Daemon
from dreamcatcher.errors import ReportableError
from dreamcatcher.state import StateDirectory

ISSUE = re.compile('gh(\\d+)\\Z', re.IGNORECASE)
HELP_WHEN_A_VIEW_ENDS = ...
HELP_WHEN_A_VIEW_TAKES_THE_SCREEN = ...
HELP_WHEN_NOTHING_WATCHES = 'Piped, redirected or captured, it shows what is there once and returns.'

def build_parser() -> argparse.ArgumentParser:
    ...

def _take_an_issue(parser: argparse.ArgumentParser) -> None:
    ...

def main(argv: Sequence[str] | None) -> int:
    ...

def _run(args: argparse.Namespace) -> None:
    ...

def _show_board(args: argparse.Namespace) -> None:
    ...

def _show_session(args: argparse.Namespace) -> None:
    ...

def _show_feed(args: argparse.Namespace) -> None:
    ...

def _find_state(root: Path) -> StateDirectory:
    ...

def _read_issue(given: str) -> int:
    ...
