# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/clock.py

from collections.abc import Callable
from datetime import UTC, datetime

type Wait = Callable[[float], None]

def now() -> datetime:
    ...
