# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/clock.py

from datetime import UTC, datetime, timedelta

MINUTE = 60
HOUR = 60
DAY = 24

def now() -> datetime:
    ...

def describe_span(span: timedelta) -> str:
    ...
