# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/codex.py

from typing import ClassVar
from dreamcatcher.adapters import Adapter, Invocation, Launch
from dreamcatcher.feed import Event, Note, Prose

NETWORK_ACCESS = 'sandbox_workspace_write.network_access=true'
STDIN = '-'
RESUME_PERMISSIONS = ...
CODEX = Codex()

def _settings(launch: Launch) -> list[str]:
    ...

def _overrides(*settings: str) -> list[str]:
    ...

def _item(item: dict) -> list[Event]:
    ...

def _command(item: dict) -> list[Event]:
    ...

def _usage(counts: dict) -> Note:
    ...

class Codex(Adapter):
    program: ClassVar[str] = 'codex'

    def build_first_round(self, launch: Launch) -> Invocation:
        ...

    def build_resumed_round(self, launch: Launch) -> Invocation:
        ...

    def build_hand_resume(self) -> list[str]:
        ...

    def _events(self, streamed: dict) -> list[Event]:
        ...
