# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/commands.py

import subprocess
from pathlib import Path
from shutil import which
from dreamcatcher.errors import ReportableError

def locate(program: str) -> str:
    ...

def run(program: str, *arguments: str, cwd: Path | None) -> str:
    ...

class CommandError(ReportableError):
    ...
