# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/commands.py

import subprocess
from contextlib import ExitStack
from dataclasses import dataclass
from pathlib import Path, PurePath
from shutil import which
from typing import IO, cast
from dreamcatcher import teardown
from dreamcatcher.errors import ReportableError

BATCH_ENDINGS = ('.cmd', '.bat')
UNQUOTABLE = {'%': 'a percent sign', '\n': 'a newline', '\r': 'a carriage return'}

def refuse_unquotable(text: str) -> str:
    ...

def locate(program: str) -> str:
    ...

def run(program: str, *arguments: str, cwd: Path | None) -> str:
    ...

def spawn(program: str, *arguments: str, cwd: Path, stdin: Path | None) -> Child:
    ...

def _build(program: str, arguments: tuple[str, ...]) -> list[str] | str:
    ...

def _quote(part: str) -> str:
    ...

class CommandError(ReportableError):
    ...

class Child:
    out: IO[str]
    err: IO[str]
    process: subprocess.Popen[str]
    pid: int

    def wait(self) -> int:
        ...

    def kill(self) -> None:
        ...
