# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/commands.py

import subprocess
from dataclasses import dataclass
from pathlib import Path, PurePath
from shutil import which
from typing import IO, cast
from dreamcatcher.errors import ReportableError

BATCH_ENDINGS = ('.cmd', '.bat')

def locate(program: str) -> str:
    ...

def run(program: str, *arguments: str, cwd: Path | None) -> str:
    ...

def spawn(program: str, *arguments: str, cwd: Path) -> Child:
    ...

def _built(program: str, arguments: tuple[str, ...]) -> list[str] | str:
    ...

def _quoted(part: str) -> str:
    ...

class CommandError(ReportableError):
    ...

class Child:
    out: IO[str]
    err: IO[str]
    process: subprocess.Popen[str]
    pid: int

    def wait(self) -> int:
        ...
