# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/config.py

from enum import StrEnum
from pathlib import Path
from typing import Annotated, Self
from pydantic import AfterValidator, ConfigDict, Field, PositiveInt, model_validator
from dreamcatcher.commands import refuse_unquotable
from dreamcatcher.documents import Document, read_toml

CONFIG_NAME = 'dreamcatcher.toml'
QuotableText = Annotated[str, AfterValidator(refuse_unquotable)]

def read_config(root: Path) -> Config:
    ...

class Harness(StrEnum):
    CLAUDE = 'claude'
    CODEX = 'codex'

class HarnessSettings(Document):
    prompt: str
    model: QuotableText
    effort: QuotableText

class DispatchMapping(Document):
    model_config = ConfigDict(extra='allow')
    __pydantic_extra__: dict[Harness, HarnessSettings]
    label: str
    harness_settings: dict[Harness, HarnessSettings]

    def choose_harness(self, named: Harness) -> Harness:
        ...

    def _carries_a_block(self) -> Self:
        ...

class Config(Document):
    interval: PositiveInt = 120
    max_agents: PositiveInt = 1
    assignee: str = '@me'
    dispatch: list[DispatchMapping] = Field(min_length=1)

    def _each_label_maps_once(self) -> Self:
        ...
