# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/config.py

from enum import StrEnum
from pathlib import Path
from typing import Self
from pydantic import Field, PositiveInt, model_validator
from dreamcatcher.documents import Document, read_toml

CONFIG_NAME = 'dreamcatcher.toml'

def read_config(root: Path) -> Config:
    ...

class Harness(StrEnum):
    CLAUDE = 'claude'
    CODEX = 'codex'

class HarnessSettings(Document):
    prompt: str
    model: str
    effort: str

class DispatchMapping(Document):
    label: str
    harness: Harness | None = None
    claude: HarnessSettings | None = None
    codex: HarnessSettings | None = None
    settings: dict[Harness, HarnessSettings]

    def settings_for(self, run_harness: Harness) -> HarnessSettings:
        ...

    def _carries_every_block_it_can_dispatch_with(self) -> Self:
        ...

class Config(Document):
    interval: PositiveInt = 120
    harness: Harness
    max_agents: PositiveInt = 1
    assignee: str = '@me'
    dispatch: list[DispatchMapping] = Field(min_length=1)

    def _each_label_maps_once(self) -> Self:
        ...
