# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/daemon.py

from collections.abc import Callable
from contextlib import suppress
from datetime import datetime
from pathlib import Path
from time import sleep
from dreamcatcher.clock import now
from dreamcatcher.commands import locate
from dreamcatcher.config import Harness, read_config
from dreamcatcher.documents import write_json
from dreamcatcher.errors import ReportableError
from dreamcatcher.harnesses import ADAPTERS
from dreamcatcher.lock import hold
from dreamcatcher.state import LastTick, StateDirectory

class Daemon:
    def __init__(self, root: Path, harness: Harness, clock: Callable[[], datetime], wait: Callable[[float], None]) -> None:
        ...

    def run(self) -> None:
        ...

    def _locate_harnesses(self) -> None:
        ...

    def tick(self) -> None:
        ...
