# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/daemon.py

from collections.abc import Callable
from contextlib import suppress
from datetime import datetime, timedelta
from pathlib import Path
from time import sleep
from dreamcatcher import teardown
from dreamcatcher.adapters import Launch
from dreamcatcher.clock import now
from dreamcatcher.commands import locate
from dreamcatcher.config import Harness, read_config
from dreamcatcher.documents import write_json
from dreamcatcher.eligibility import judge_issues
from dreamcatcher.errors import ReportableError
from dreamcatcher.github import Unknown, identify_account, identify_repository
from dreamcatcher.harnesses import ADAPTERS
from dreamcatcher.lock import hold
from dreamcatcher.resumes import Finding, Resume, find_resume, list_waiting, sort_resumes
from dreamcatcher.rounds import Cause, Round
from dreamcatcher.sessions import Session, advance_watermark, create_session, discard_session, read_sessions
from dreamcatcher.state import CandidateIssue, LastTick, StateDirectory, Waiting

COOLDOWN = timedelta(minutes=15)

def _check_cooldown(sessions: list[Session], at: datetime) -> str | None:
    ...

class Daemon:
    def __init__(self, root: Path, harness: Harness, clock: Callable[[], datetime], wait: Callable[[float], None]) -> None:
        ...

    def run(self) -> None:
        ...

    def tick(self, repository: str, account: str) -> None:
        ...

    def _identify_repository(self) -> str:
        ...

    def _identify_account(self) -> str:
        ...

    def _decide_and_launch(self, repository: str, account: str, at: datetime) -> LastTick:
        ...

    def _reconcile(self, repository: str, account: str, sessions: list[Session]) -> list[Finding]:
        ...

    def _resume_session(self, at: datetime, resume: Resume, found: list[Finding]) -> LastTick:
        ...

    def _launch_resume(self, resume: Resume) -> None:
        ...

    def _dispatch_oldest_issue(self, at: datetime, judged: list[CandidateIssue], waiting: list[Waiting]) -> LastTick:
        ...

    def _launch_session(self, candidate: CandidateIssue, at: datetime) -> str:
        ...

    def _locate_harnesses(self) -> None:
        ...

    def _sweep_orphans(self) -> None:
        ...
