# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/documents.py

import tomllib
from pathlib import Path
from pydantic import BaseModel, ConfigDict, ValidationError
from pydantic_core import ErrorDetails

def read_toml(model: type[DocumentT], path: Path) -> DocumentT:
    ...

def _report(path: Path, error: ValidationError) -> str:
    ...

def _phrase(detail: ErrorDetails) -> str:
    ...

def _split(location: tuple[int | str, ...]) -> tuple[tuple[int | str, ...], str | None]:
    ...

def _place(location: tuple[int | str, ...]) -> str:
    ...

def _fault(detail: ErrorDetails, setting: str | None) -> str:
    ...

class Document(BaseModel):
    model_config = ConfigDict(extra='forbid', frozen=True)

class DocumentError(Exception):
    ...
