# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/documents.py

import tomllib
from pathlib import Path
from pydantic import BaseModel, ConfigDict, ValidationError
from dreamcatcher.errors import ReportableError

def read_toml(model: type[DocumentT], path: Path) -> DocumentT:
    ...

def write_json(document: Document, path: Path) -> None:
    ...

def _report(path: Path, error: ValidationError) -> str:
    ...

class Document(BaseModel):
    model_config = ConfigDict(extra='forbid', frozen=True)

class DocumentError(ReportableError):
    ...
