# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/documents.py

import tomllib
from pathlib import Path
from pydantic import BaseModel, ConfigDict, ValidationError
from dreamcatcher.errors import ReportableError

WRITING = '.writing'

def read_toml(model: type[DocumentT], path: Path) -> DocumentT:
    ...

def read_json(model: type[DocumentT], path: Path) -> DocumentT:
    ...

def read_text(path: Path) -> str:
    ...

def write_text(text: str, path: Path) -> None:
    ...

def append_text(text: str, path: Path) -> None:
    ...

def write_json(document: Document, path: Path) -> None:
    ...

def _decode(read: bytes, path: Path) -> str:
    ...

def _write(text: str, path: Path, mode: str) -> None:
    ...

def _report(path: Path, error: ValidationError) -> str:
    ...

class Document(BaseModel):
    model_config = ConfigDict(extra='forbid', frozen=True)
