# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/eligibility.py

from collections import defaultdict
from dreamcatcher.config import Config
from dreamcatcher.github import BlockerState, Issue, Unknown, list_blockers, list_issues, list_linked_pull_requests
from dreamcatcher.state import Candidate

def judge_issues(repository: str, config: Config, claimed: set[int]) -> list[Candidate] | Unknown:
    ...

def _list_issues(repository: str, config: Config) -> list[tuple[Issue, list[str]]] | Unknown:
    ...

def _find_obstacle(repository: str, issue: int, labels: list[str], claimed: set[int]) -> str | None:
    ...

def _check_pull_requests(repository: str, issue: int) -> str | None:
    ...

def _check_blockers(repository: str, issue: int) -> str | None:
    ...
