# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/eligibility.py

from collections import defaultdict
from dreamcatcher.config import Config
from dreamcatcher.github import BlockerState, Issue, Unknown, blockers, issues, linked_pull_requests
from dreamcatcher.state import Candidate

def judge_issues(repository: str, config: Config, claimed: set[int]) -> list[Candidate] | Unknown:
    ...

def _list_issues(repository: str, config: Config) -> list[tuple[str, Issue]] | Unknown:
    ...

def _obstacle(repository: str, issue: int, labels: list[str], claimed: set[int]) -> str | None:
    ...

def _claim(repository: str, issue: int) -> str | None:
    ...

def _blocker(repository: str, issue: int) -> str | None:
    ...
