# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/feed.py

from collections.abc import Callable
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path, PurePath
from dreamcatcher.clock import now
from dreamcatcher.documents import read_text
from dreamcatcher.words import STAMP, describe_time

WIDTH = 200
INDENT = '  '
GAP = '  '
type Event = Note | Prose

def compose_round_boundary(number: int, cause: str, at: datetime) -> Line:
    ...

def read_feed_line(written: str) -> Line | None:
    ...

def read_last_feed_line(path: Path) -> Line | None:
    ...

class Line:
    at: datetime
    text: str

    def render(self) -> str:
        ...

class Note:
    label: str
    detail: str = ''
    is_subagent: bool = False

class Prose:
    text: str
    is_subagent: bool = False

class Renderer:
    worktree: PurePath
    clock: Callable[[], datetime] = now

    def render(self, event: Event) -> str:
        ...

    def _render_note(self, note: Note) -> str:
        ...

    def _shorten(self, detail: str) -> str:
        ...

    def _strip_worktree(self, detail: str) -> str:
        ...

    def _stamp(self, contents: list[str], is_subagent: bool) -> str:
        ...
