# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/feed.py

from collections.abc import Callable
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import PurePath
from dreamcatcher.clock import now

WIDTH = 200
INDENT = '  '
type Event = Note | Prose

class Note:
    label: str
    detail: str = ''
    subagent: bool = False

class Prose:
    text: str
    subagent: bool = False

class Renderer:
    worktree: PurePath
    clock: Callable[[], datetime] = now

    def boundary(self, number: int, cause: str) -> str:
        ...

    def render(self, event: Event) -> str:
        ...

    def _render_note(self, note: Note) -> str:
        ...

    def _shorten(self, detail: str) -> str:
        ...

    def _strip_worktree(self, detail: str) -> str:
        ...

    def _stamp(self, contents: list[str], subagent: bool) -> str:
        ...
