# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/git.py

from pathlib import Path
from dreamcatcher.commands import run

def fetch(root: Path) -> None:
    ...

def add_worktree(root: Path, path: Path, branch: str) -> None:
    ...

def remove_worktree(root: Path, path: Path) -> None:
    ...

def delete_branch(root: Path, branch: str) -> None:
    ...
