# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/git.py

from contextlib import suppress
from pathlib import Path
from dreamcatcher.commands import CommandError, run

def fetch(root: Path) -> None:
    ...

def add_worktree(root: Path, path: Path, branch: str) -> None:
    ...

def discard_worktree(root: Path, path: Path, branch: str) -> None:
    ...
