# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/github.py

from dataclasses import dataclass
from datetime import datetime
from enum import StrEnum
from pathlib import Path
from pydantic import BaseModel, ConfigDict, Field, TypeAdapter, ValidationError
from dreamcatcher.commands import CommandError, run

LISTING_LIMIT = '500'
REPOSITORY = TypeAdapter(Repository)
ACCOUNT = TypeAdapter(Account)
ISSUES = TypeAdapter(list[Issue])
PULL_REQUESTS = TypeAdapter(list[PullRequest])
BLOCKERS = TypeAdapter(list[Blocker])

def identify(root: Path) -> str | Unknown:
    ...

def login() -> str | Unknown:
    ...

def issues(repository: str, *, label: str, assignee: str) -> list[Issue] | Unknown:
    ...

def pull_requests(repository: str, branch: str) -> list[PullRequest] | Unknown:
    ...

def blockers(repository: str, issue: int) -> list[Blocker] | Unknown:
    ...

def _read(shape: TypeAdapter[ReadT], *arguments: str, cwd: Path | None) -> ReadT | Unknown:
    ...

class Unknown:
    reason: str

class Projection(BaseModel):
    model_config = ConfigDict(frozen=True, populate_by_name=True)

class PullRequestState(StrEnum):
    OPEN = 'OPEN'
    CLOSED = 'CLOSED'
    MERGED = 'MERGED'

class BlockerState(StrEnum):
    OPEN = 'open'
    CLOSED = 'closed'

class Repository(Projection):
    name_with_owner: str = Field(alias='nameWithOwner')

class Account(Projection):
    login: str

class Issue(Projection):
    number: int
    created_at: datetime = Field(alias='createdAt')

class PullRequest(Projection):
    number: int
    state: PullRequestState

class Blocker(Projection):
    number: int
    state: BlockerState
