# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/github.py

from dataclasses import dataclass
from datetime import datetime
from enum import StrEnum
from itertools import chain
from pathlib import Path
from typing import Any, Literal
from pydantic import AliasChoices, AliasPath, BaseModel, ConfigDict, Field, TypeAdapter, ValidationError, model_validator
from dreamcatcher.commands import CommandError, run

LISTING_LIMIT = '500'
PAGE_SIZE = '100'
SPEAKING_VERDICTS = frozenset({Verdict.APPROVED, Verdict.CHANGES_REQUESTED})
type AnyPost = Comment | Review | InlineComment
REPOSITORY = TypeAdapter(Repository)
ACCOUNT = TypeAdapter(Account)
ISSUES = TypeAdapter(list[Issue])
PULL_REQUESTS = TypeAdapter(list[PullRequest])
BLOCKERS = TypeAdapter(list[Blocker])
LINKED = TypeAdapter(Linked)
CONVERSATION = TypeAdapter(list[list[Comment]])
REVIEWS = TypeAdapter(list[list[Review]])
INLINE_COMMENTS = TypeAdapter(list[list[InlineComment]])
POST_LISTS = ...

def identify_repository(root: Path) -> str | Unknown:
    ...

def identify_account() -> str | Unknown:
    ...

def list_issues(repository: str, *, label: str, assignee: str) -> list[Issue] | Unknown:
    ...

def list_pull_requests(repository: str, branch: str) -> list[PullRequest] | Unknown:
    ...

def list_linked_pull_requests(repository: str, issue: int) -> list[LinkedPullRequest] | Unknown:
    ...

def list_blockers(repository: str, issue: int) -> list[Blocker] | Unknown:
    ...

def list_posts(repository: str, pull_request: int) -> list[AnyPost] | Unknown:
    ...

def _read_pages(shape: TypeAdapter[list[list[PostT]]], path: str) -> list[AnyPost] | Unknown:
    ...

def _read(shape: TypeAdapter[ReadT], *arguments: str, cwd: Path | None) -> ReadT | Unknown:
    ...

class Unknown:
    reason: str

class Projection(BaseModel):
    model_config = ConfigDict(frozen=True, populate_by_name=True)

class PullRequestState(StrEnum):
    OPEN = 'OPEN'
    CLOSED = 'CLOSED'
    MERGED = 'MERGED'

class BlockerState(StrEnum):
    OPEN = 'open'
    CLOSED = 'closed'

class Verdict(StrEnum):
    APPROVED = 'APPROVED'
    CHANGES_REQUESTED = 'CHANGES_REQUESTED'
    COMMENTED = 'COMMENTED'
    DISMISSED = 'DISMISSED'
    PENDING = 'PENDING'

class Repository(Projection):
    name_with_owner: str = Field(alias='nameWithOwner')

class Account(Projection):
    login: str

class Issue(Projection):
    number: int
    created_at: datetime = Field(alias='createdAt')

class PullRequest(Projection):
    number: int
    state: PullRequestState

class Blocker(Projection):
    number: int
    state: BlockerState

class LinkedPullRequest(Projection):
    number: int

class Linked(Projection):
    pull_requests: list[LinkedPullRequest] = Field(alias='closedByPullRequestsReferences')

class Post(Projection):
    id: int
    author: str = Field(default='', validation_alias=AliasPath('user', 'login'))
    written_at: str = Field(default='', validation_alias=AliasChoices('created_at', 'submitted_at'))
    body: str = ''
    is_speaking: bool

class Comment(Post):
    kind: Literal['comment'] = 'comment'

class Review(Post):
    kind: Literal['review'] = 'review'
    verdict: Verdict = Field(alias='state')
    is_speaking: bool

class InlineComment(Post):
    kind: Literal['inlineComment'] = 'inlineComment'
    path: str
    side: str
    line: int | None = None
    start_line: int | None = None
    diff_hunk: str

    def _fall_back_to_the_original_lines(cls, document: Any) -> Any:
        ...
