# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/harnesses.py

from dreamcatcher.adapters import Adapter
from dreamcatcher.claude import CLAUDE
from dreamcatcher.codex import CODEX
from dreamcatcher.config import Harness

ADAPTERS: dict[Harness, Adapter] = {Harness.CLAUDE: CLAUDE, Harness.CODEX: CODEX}
