# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/lock.py

import os
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path
import psutil
from dreamcatcher.documents import write_text
from dreamcatcher.errors import ReportableError

def hold(path: Path) -> Iterator[None]:
    ...

def _holder(path: Path) -> int | None:
    ...
