# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/prompts.py

MARKER = '<!-- dreamcatcher -->'
ISSUE_PLACEHOLDER = '{issue}'
POSTSCRIPT = ...

def compose_first_round_prompt(template: str, issue: int) -> str:
    ...
