# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/relay.py

from dreamcatcher.github import Post, Unknown, list_posts
from dreamcatcher.prompts import MARKER

def peek_new_posts(repository: str, pull_request: int, *, account: str, watermark: str) -> list[Post] | Unknown:
    ...

def _is_new_from_user(post: Post, account: str, watermark: str) -> bool:
    ...
