# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/resumes.py

from dataclasses import dataclass
from dreamcatcher.github import AnyPost, PullRequest, PullRequestState, Unknown, list_pull_requests
from dreamcatcher.prompts import CARRY_ON_PROMPT, compose_inbox_prompt
from dreamcatcher.relay import Inbox, peek_new_posts
from dreamcatcher.rounds import Cause
from dreamcatcher.sessions import Session
from dreamcatcher.state import Waiting

type Finding = Resume | Waiting
PRIORITY = (Cause.CARRY_ON, Cause.FINAL, Cause.POSTS)

def sort_resumes(found: list[Resume]) -> list[Resume]:
    ...

def list_waiting(found: list[Finding]) -> list[Waiting]:
    ...

def find_resume(repository: str, account: str, session: Session) -> Finding | None:
    ...

def _check_last_round(session: Session) -> str | None:
    ...

def _find_pull_request_resume(repository: str, account: str, session: Session) -> Finding | None:
    ...

def _choose_pull_request(found: list[PullRequest]) -> PullRequest | None:
    ...

def _has_run_final_round(session: Session) -> bool:
    ...

def _compose_resume(session: Session, pull_request: PullRequest, posted: list[AnyPost]) -> Resume:
    ...

def _count_posts(posted: list[AnyPost]) -> str:
    ...

def _wait(session: Session, reason: str) -> Waiting:
    ...

class Resume:
    session: Session
    cause: Cause
    reason: str
    prompt: str
    inbox: Inbox | None = None
    newest_post: str
