# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/rounds.py

from collections.abc import Callable
from dataclasses import dataclass
from datetime import datetime
from enum import StrEnum
from pathlib import Path
from threading import Event as Flag
from threading import Lock, Thread
from pydantic import PositiveInt
from dreamcatcher.adapters import Adapter, Invocation
from dreamcatcher.clock import now
from dreamcatcher.commands import spawn
from dreamcatcher.documents import Document, append_text, read_json, write_json, write_text
from dreamcatcher.errors import ReportableError
from dreamcatcher.feed import Event, Prose, Renderer

RECORD = 'round.json'

class Cause(StrEnum):
    DISPATCH = 'dispatched'
    CARRY_ON = 'carried on'
    POSTS = 'new posts'
    FINAL = 'final round'

class Ending(Document):
    at: datetime
    status: int
    is_failed: bool

class RoundRecord(Document):
    started: datetime
    pid: PositiveInt
    cause: Cause
    ending: Ending | None = None
    is_complete: bool

class Workspace:
    worktree: Path
    directory: Path
    prompt: Path
    record: Path
    feed: Path
    raw: Path
    inbox: Path

class RoundReader:
    def __init__(self) -> None:
        ...

    def read_records(self, *, directory: Path) -> list[RoundRecord]:
        ...

    def _read_record(self, *, path: Path) -> RoundRecord:
        ...

class Round:
    is_alive: bool

    def __init__(self, *, adapter: Adapter, invocation: Invocation, workspace: Workspace, cause: Cause, clock: Callable[[], datetime]) -> None:
        ...

    def wait(self) -> None:
        ...

    def stop(self) -> None:
        ...

    def _interrupt(self) -> None:
        ...

    def _pump(self, *, read: Callable[[], None]) -> None:
        ...

    def _read_stdout(self) -> None:
        ...

    def _read_stderr(self) -> None:
        ...

    def _close(self) -> None:
        ...

    def _append(self, *, line: str, events: list[Event]) -> None:
        ...
