# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/rounds.py

from collections.abc import Callable
from datetime import datetime
from pathlib import Path
from threading import Lock, Thread
from dreamcatcher.adapters import Adapter
from dreamcatcher.clock import now
from dreamcatcher.commands import spawn
from dreamcatcher.documents import Document, append_text, write_json
from dreamcatcher.errors import ReportableError
from dreamcatcher.feed import Prose, Renderer

class RoundRecord(Document):
    started: datetime
    pid: int
    ended: datetime | None = None
    status: int | None = None

class Round:
    record: Path
    feed: Path
    raw: Path
    alive: bool

    def __init__(self, adapter: Adapter, command: list[str], worktree: Path, directory: Path, clock: Callable[[], datetime]) -> None:
        ...

    def wait(self) -> None:
        ...

    def stop(self) -> None:
        ...

    def _pump(self, read: Callable[[], None]) -> None:
        ...

    def _read_stdout(self) -> None:
        ...

    def _read_stderr(self) -> None:
        ...

    def _close(self) -> None:
        ...

    def _rendered(self, line: str) -> str:
        ...

    def _passed(self, line: str) -> str:
        ...

    def _append(self, line: str, render: Callable[[str], str]) -> None:
        ...
