# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/scry.py

from collections.abc import Callable
from datetime import datetime
from rich.console import Console
from rich.padding import Padding
from rich.table import Table
from rich.text import Text
from dreamcatcher.board import Board, Standing, read_board
from dreamcatcher.clock import describe_span, now
from dreamcatcher.state import StateDirectory

COLOURS = ...
QUEUE = 'queued'
INDENT = (0, 0, 0, 2)

def open_console() -> Console:
    ...

def show_board(state: StateDirectory, console: Console, clock: Callable[[], datetime]) -> None:
    ...

def _describe_daemon(board: Board) -> Text:
    ...

def _show_attempts(console: Console, board: Board, standing: Standing) -> None:
    ...

def _show_queue(console: Console, board: Board) -> None:
    ...

def _open_table() -> Table:
    ...

def _print_section(console: Console, heading: str, colour: str, table: Table) -> None:
    ...
