# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/sessions.py

from contextlib import suppress
from dataclasses import dataclass, field
from datetime import datetime
from functools import cached_property
from pathlib import Path
from dreamcatcher import prompts
from dreamcatcher.commands import CommandError
from dreamcatcher.config import DispatchMapping, Harness
from dreamcatcher.documents import Document, read_json, read_text, write_json, write_text
from dreamcatcher.errors import ReportableError
from dreamcatcher.git import add_worktree, delete_branch, fetch, remove_worktree
from dreamcatcher.rounds import Cause, RoundReader, RoundRecord, Workspace
from dreamcatcher.state import StateDirectory

BRANCH_PREFIX = 'dreamcatcher-'
RECORD = 'session.json'
ROUNDS = 'rounds'
WATERMARK = 'watermark'

def read_sessions(state: StateDirectory, reader: RoundReader | None) -> list[Session]:
    ...

def create_session(state: StateDirectory, mapping: DispatchMapping, named: Harness, issue: int, at: datetime) -> Session:
    ...

def _read_session(directory: Path, reader: RoundReader) -> Session:
    ...

def _read_watermark(directory: Path) -> str:
    ...

def advance_watermark(session: Session, newest: str) -> None:
    ...

def discard_session(state: StateDirectory, record: SessionRecord) -> None:
    ...

class SessionRecord(Document):
    issue: int
    label: str
    branch: str
    worktree: Path
    harness: Harness
    model: str
    effort: str
    prompt: str

class Session:
    directory: Path
    record: SessionRecord
    watermark: str = ''
    reader: RoundReader = field(default_factory=RoundReader, compare=False, repr=False)
    key: str
    has_run_final_round: bool
    next_workspace: Workspace

    def rounds(self) -> list[RoundRecord]:
        ...

    def describe_unfinished_round(self) -> str | None:
        ...

    def workspace(self, number: int) -> Workspace:
        ...
