# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/state.py

from dataclasses import dataclass
from pathlib import Path

STATE_DIRECTORY = '.dreamcatcher'

class StateDirectory:
    root: Path
    path: Path
    lock: Path
    last_tick: Path

    def bootstrap(self) -> None:
        ...
