# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/state.py

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from dreamcatcher.documents import Document, write_text

STATE_DIRECTORY = '.dreamcatcher'

class Candidate(Document):
    issue: int
    reason: str | None = None
    is_eligible: bool

class LastTick(Document):
    at: datetime

class StateDirectory:
    root: Path
    path: Path
    lock: Path
    last_tick: Path
    worktrees: Path
    sessions: Path

    def bootstrap(self) -> None:
        ...
