# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/tui.py

from collections.abc import Callable, Iterable
from contextlib import suppress
from dataclasses import dataclass, field
from datetime import datetime
from time import sleep
from rich.console import Console, Group, RenderableType
from rich.padding import Padding
from rich.table import Table
from rich.text import Text
from dreamcatcher.board import Board, SessionRow, SessionStanding, read_board, read_rows_for_issue
from dreamcatcher.clock import now
from dreamcatcher.documents import read_lines_from
from dreamcatcher.errors import ReportableError
from dreamcatcher.feed import GAP, Line, compose_round_boundary, read_feed_line
from dreamcatcher.harnesses import ADAPTERS
from dreamcatcher.rounds import RoundRecord
from dreamcatcher.sessions import Session
from dreamcatcher.state import StateDirectory
from dreamcatcher.words import describe_count, describe_span, describe_time

COLOURS = ...
QUEUE = 'queued'
OVER = (SessionStanding.DONE, SessionStanding.STUCK)
PAUSE = 1.0
LABEL = '^\\s*\\[[^\\]]+\\]'
INDENT = (0, 0, 0, 2)

def open_console() -> Console:
    ...

def show_board(state: StateDirectory, console: Console, clock: Callable[[], datetime]) -> None:
    ...

def render_board(state: StateDirectory, clock: Callable[[], datetime]) -> RenderableType:
    ...

def _render_parts(*parts: RenderableType | None) -> RenderableType:
    ...

def _describe_daemon(board: Board) -> Text:
    ...

def _render_rows(board: Board, standing: SessionStanding) -> RenderableType | None:
    ...

def _describe_round(row: SessionRow) -> str:
    ...

def _render_detail(row: SessionRow, prefix: str, continuation_indent: int, style: str) -> RenderableType:
    ...

def _render_queue(board: Board) -> RenderableType | None:
    ...

def _describe_nothing_dispatched(board: Board) -> Text | None:
    ...

def _open_table() -> Table:
    ...

def _render_section(heading: str, colour: str, body: RenderableType) -> RenderableType:
    ...

def show_session(state: StateDirectory, issue: int, console: Console, clock: Callable[[], datetime]) -> None:
    ...

def render_session(state: StateDirectory, issue: int, clock: Callable[[], datetime]) -> RenderableType:
    ...

def _render_vitals(state: StateDirectory, row: SessionRow) -> RenderableType:
    ...

def _render_rounds(row: SessionRow) -> RenderableType | None:
    ...

def _describe_run(record: RoundRecord) -> str:
    ...

def _describe_ending(record: RoundRecord, is_running: bool) -> str:
    ...

def _render_hand_resume(state: StateDirectory, row: SessionRow) -> RenderableType | None:
    ...

def _render_older_sessions(older: list[SessionRow]) -> RenderableType | None:
    ...

def show_feed(state: StateDirectory, issue: int, console: Console, round_number: int | None, wait: Callable[[float], None]) -> None:
    ...

def _is_watched(console: Console) -> bool:
    ...

def _keep_looking(look: Callable[[], bool], wait: Callable[[float], None]) -> None:
    ...

def _show_one_round(state: StateDirectory, issue: int, number: int, console: Console) -> None:
    ...

def _find_rows_for_issue(state: StateDirectory, issue: int, clock: Callable[[], datetime]) -> list[SessionRow]:
    ...

def _paint_written(written: str) -> Text:
    ...

def _paint(line: Line, said: Text) -> Text:
    ...

class _FeedView:
    console: Console
    positions: dict[int, int] = field(default_factory=dict)

    def show_what_arrived(self, session: Session, round_numbers: Iterable[int]) -> None:
        ...

    def _show_round_heading(self, session: Session, round_number: int) -> None:
        ...

    def _show_new_lines(self, session: Session, round_number: int) -> None:
        ...
