# Generated by uncoded — do not edit; regeneration overwrites.
# src/dreamcatcher/wakeups.py

from dataclasses import dataclass
from dreamcatcher.github import AnyPost, PullRequest, PullRequestState, Unknown, list_pull_requests
from dreamcatcher.prompts import CARRY_ON_PROMPT, compose_inbox_prompt
from dreamcatcher.relay import Inbox, peek_new_posts
from dreamcatcher.rounds import Cause
from dreamcatcher.sessions import Session
from dreamcatcher.state import WaitingSession

type Finding = Wakeup | WaitingSession
PRIORITY = (Cause.CARRY_ON, Cause.FINAL, Cause.POSTS)

def sort_wakeups(found: list[Wakeup]) -> list[Wakeup]:
    ...

def list_waiting(found: list[Finding]) -> list[WaitingSession]:
    ...

def judge_session(repository: str, account: str, session: Session) -> Finding | None:
    ...

def _judge_pull_request(repository: str, account: str, session: Session) -> Finding | None:
    ...

def _choose_pull_request(found: list[PullRequest]) -> PullRequest | None:
    ...

def _compose_resume(session: Session, pull_request: PullRequest, posted: list[AnyPost]) -> Wakeup:
    ...

def _count_posts(posted: list[AnyPost]) -> str:
    ...

def _wait(session: Session, reason: str) -> WaitingSession:
    ...

class Wakeup:
    session: Session
    cause: Cause
    reason: str
    prompt: str
    inbox: Inbox | None = None
    newest_post: str
